apiVersion: v1
kind: Service
metadata:
  name: feedback-app-frontend-service
spec:
  selector:
    app: feedback-app-frontend
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: feedback-app-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feedback-app-frontend
  template:
    metadata:
      labels:
        app: feedback-app-frontend
        environment: test
    spec:
      containers:
      - name: feedback-app-frontend-api
        image: kuigan/feedback-app-frontend:v1.0
        resources:
          requests:
            memory: "64Mi"
            cpu: "125m"
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 80
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /feedback 
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 5
          successThreshold: 1

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: feedback-app-frontend-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: feedback-app-frontend
  minReplicas: 1
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
